AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Express app on AWS Lambda

Resources:
  ExpressFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler        # 👈 points to backend/lambda.js (exports.handler)
      Runtime: nodejs18.x
      CodeUri: .                     # 👈 package the code in this folder
      Timeout: 10
      MemorySize: 512
      Events:                        # 👈 attach API Gateway trigger
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
