name: Deploy Express to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        working-directory: backend
        run: npm install --production

      - name: Zip backend for Lambda
        run: |
          cd backend
          zip -r ../function.zip . -x "*.git*" "test/*" "*.DS_Store"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1 # change to your region

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name file-upload-function \
            --zip-file fileb://function.zip
